name: Base

on:
  workflow_call:
    inputs:
      dotEnvSecretName:
        required: true
        type: string

jobs:
  # Build job
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
  
      - name: Cache Dependency
        uses: actions/cache@v4
        id: cache_dependency
        env:
          cache-name: cache-dependency
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Echo
        run: echo Hello World $NUXT_PUBLIC_TITLE

      - name: Nuxt Build
        run: npm run build
