name: 開発環境

on:
  workflow_dispatch:
    inputs:
      environment: # Deploy先を選択できるようにする
        required: true
        type: choice
        options:
          - 'dev'
          - 'stg'
          - 'prod'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    secrets: inherit
    environment: ${{ inputs.environment }}
    uses: './.github/workflows/_template.yml'
    with:
      dotEnvSecretName: DOT_ENV_DEV

